### ISSUE TITLE
Test driver seems to not read all of dictionaries in Python driver

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#2887]
Off next, `test/rql_test/src/regression/2838.yaml` is defined as so:

``` yaml
desc: Test that return_changes fails gracefully.
tests:
  - py: r.table_create('2838')
    ot: ({'created':1})

  - py: r.table('2838').insert([{'result':i} for i in range(1,100)]).pluck('first_error', 'inserted')
    ot: ({'inserted':99})

  - py: r.table('2838').update({'foo':'bar'}, return_changes=True)['changes'].count()
    runopts:
      array_limit: '40'
    ot: (40)

  - py: r.table('2838').update({'foo':'quux'}, return_changes=True)['warnings']
    runopts:
      array_limit: '40'
    ot: (['Too many changes, array truncated to 40.'])

  - py: r.table_drop('2838')
    ot: ({'dropped':1})
```

If test #4 is changed to read

``` yaml
  - py: r.table('2838').update({'foo':'quux'}, return_changes=True)
    runopts:
      array_limit: '40'
    ot: ({'warnings':['Too many changes, array truncated to 40.']})
```

the test succeeds, even though there are many more fields returned by that expression than just `warnings`.
