### ISSUE TITLE
Ruby tests don't catch cases where we should error but don't

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4560]
Here's a simple Yaml test that demonstrates this:
```
desc: This should fail, but doesn't
tests:
  - rb: r.expr(1)
    ot: err("RqlCompileError", "Test")
```

This test passes in `next`, but I'd expect it to fail.
