### ISSUE TITLE
How to mock rethinkdb for unit testing DAOs

### ISSUE THREAD

**Issue by gyowanny** [rethinkdb/rethinkdb#6324]
Hi,
What is the best approach to mock / stub rethinkdb in order to unit test my DAO's with NodeJS?
Examples are welcome.

Cheers,

Gyo

**Comment by jeffijoe** [comment]
My approach to testing my DAO's with RethinkDB is simply to run a RethinkDB in a Docker container for my tests. This gives you 100% credibility as to whether or not your queries work.

I recommend Docker Compose to make this super easy.

**Comment by gyowanny** [comment]
Hi @jeffijoe,
Thanks for your feedback. I'm curious about your approach. Do you spin up the docker image via npm script? Or do you use something like docker-run?

Cheers

**Comment by jeffijoe** [comment]
I have 2 terminals, one for my tests and another for docker-compose.

Here's my `docker-compose.yml`:

```
version: '2'
services:
  rethink:
    image: rethinkdb
    ports:
      - "37250:28015"
      - "37251:29015"
      - "37252:8080"
  redis:
    image: redis
    ports:
      - "37253:6379"
```

and in another terminal, I do `docker-compose up`
