### ISSUE TITLE
Could not create directory 'rethinkdb_data': Permission denied

### ISSUE THREAD

**Issue by dchhetri** [rethinkdb/rethinkdb#6741]
Running into this issue and looking for some suggestions. I have a docker compose file setup. Something like so

````yml
version: '3'
services:
  rethinkdb:
    image: internal-artifactory.com/rethinkdb:latest
    command: rethinkdb --bind all
    container_name: 'rethinkdb'
    volumes:
      - ./.rethinkdb:/data
    ports:
      - "9119:8080"
      - "28015:28015"

  server-node:
    image: internal-artifactory.com/node:latest
    container_name: 'server-node'
    depends_on:
      - rethinkdb
    ports:
      - "3000:3000"
````

running `docker-compose up`. Spits out an error like so
````
Creating rethinkdb ... done
Creating server-node ... done
Creating server-node ... 
Attaching to rethinkdb, server-node
rethinkdb    | Could not create directory 'rethinkdb_data': Permission denied
rethinkdb exited with code 1

````
I'm not sure what the issue is. Here is the Dockerfile for rethinkdb container for reference if needed
````dockerfile
FROM internal-artifactory/ubuntu16:latest

ARG INET_PROXY

RUN apt-key adv --keyserver keys.gnupg.net --recv-keys 3B87619DF812A63A8C1005C30742918E5C8DA04A
RUN echo "deb http://download.rethinkdb.com/apt xenial main" > /etc/apt/sources.list.d/rethinkdb.list
ENV RETHINKDB_PACKAGE_VERSION 2.3.6~0xenial

RUN apt-get update \
    && apt-get install -y rethinkdb=$RETHINKDB_PACKAGE_VERSION \
    && rm -rf /var/lib/apt/lists/*

VOLUME ["/data"]
WORKDIR /data
CMD ["rethinkdb", "--bind", "all"]
EXPOSE 28015 29015 8080

````
Things I've tried that did not work.
- Add rethinkdb and www-data as user on host system 
    - Lead to same permission error.
- Manually create rethinkdb_data 
    - Lead to permission issues with other files(ex log_file create/read).
- Run rethinkdb --runuser root --rungroup root --bind all
    - Lead to same permission error.

Hoping for some suggestions to try here. Note it worked locally on my mac, just not in a dev box for some reason. 

Best.
