### ISSUE TITLE
Server will only initialize on an empty directory 

### ISSUE THREAD

**Issue by tophercullen** [rethinkdb/rethinkdb#6788]
Starting a server using a non-empty non-initialized data directory results in the following obtuse error message 

```
Running rethinkdb 2.3.6~0jessie (GCC 4.9.2)...
Running on Linux 4.14.123-111.109.amzn2.x86_64 x86_64
Loading data from directory /data/rethinkdb_data
Version: rethinkdb 2.3.6~0jessie (GCC 4.9.2)
error: Inaccessible database file: "/data/rethinkdb_data/metadata": No such file or directory
       Some possible reasons:
       - the database file couldn't be created or opened for reading and writing
       - the user which was used to start the database is not an owner of the file
```
This is not a permission or write problem.The error/failure occurs regardless any permissions. *Any* file/directory present will cause initialization to be skipped and thus startup fail. Even the presence of rethinkdb's own `log_file` will cause this. The data directory must be totally void.

On a related note, while creating an empty metadata file will get past this error, the server is non-functional and just hangs with no log output (relates to issue #5850).  Similar to a non-empty data directory, an empty metadata file won't trigger initialization and doesn't have an correctly associated logging event for the failure.

How to reproduce:

Setup dirs:
``mkdir -p /opt/mytest/rethinkdb/somedir```

Docker compose
```
version: '2.4'

services:
    rethinkdb:
        container_name: rethinkdb
        image: rethinkdb:2.3.6
        restart: always
        hostname: myhost
        command: rethinkdb --bind all 
        networks:
            - rethink
        ports:
            - "8080:8080"
            - "28015:28015"
            - "29015:29015"
        volumes:
            - /opt/mytest/rethinkdb:/data/rethinkdb_data:z

networks:
    rethink:
        driver: bridge
```
```
docker-compose -f <compose file location> up -d
docker logs rethinkdb
docker-compose -f <compose file location> down
rm -rf /opt/mytest/rethinkdb/*
docker-compose -f <compose file location> up -d
docker logs rethinkdb
```
