### ISSUE TITLE
Ubuntu-bionic release gone?

### ISSUE THREAD

**Issue by jwr** [rethinkdb/rethinkdb#6991]
I started getting "The repository 'https://download.rethinkdb.com/repository/ubuntu-bionic bionic Release' no longer has a Release file." when trying to install RethinkDB on 18.04LTS (through ansible automation).

I haven't changed anything in my repository configuration:

```
- name: Add RethinkDB repository
  apt_repository:
    repo: deb https://download.rethinkdb.com/repository/ubuntu-bionic bionic main
    state: present
```

Have the files disappeared, or been moved/renamed? I tried clicking around in the Nexus Repository manager, and the files seem to be there for bionic, but I can't make any sense of the information there, or how it maps into a URL that apt expects…

**Comment by gabor-boros** [comment]
Hello @jwr,

> Have the files disappeared, or been moved/renamed?

I checked this issue and it is not clear what has been changed, though I can clearly state that nothing changed in the Nexus repo.

If you check the package on the [download server](https://download.rethinkdb.com/#browse/browse:ubuntu-bionic:packages%2Fr%2Frethinkdb%2F2.4.1~0bionic%2Famd64%2Frethinkdb) (you have to click the `.deb` file) on the right-hand side you can see the update and creation dates are the same. That's the same for the Release files (which are there: `InRelease`, `Release`, and `Release.gpg`).

To validate this issue, I tried to install rethinkdb using an ubuntu docker image. The first thing that surprised me was the missing `keys.gnupg.net` keyserver, though that was deprecated as far as I know, so my best guess is that was decommissioned. After switching to Unbuntu's keyserver, everything went well.

To be completely fair, for the first attempt I tried to use the decommissioned keyserver, and for the second attempt, I forgot to install `ca-certificates`. Without that package, I got the same error that you get: "The repository 'https://download.rethinkdb.com/repository/ubuntu-bionic bionic Release' no longer has a Release file." which is false and misleading at the same time.

Here you can see the screen recording I made to show the steps:

[![asciicast](https://asciinema.org/a/8kaukodIF7ZPVzZMSHxJQsaH4.svg)](https://asciinema.org/a/8kaukodIF7ZPVzZMSHxJQsaH4)

These commands were executed during the recording:

```shell
apt update && apt install -y gnupg ca-certificates
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "539A 3A8C 6692 E6E3 F69B 3FE8 1D85 E93F 801B B43F"
echo "deb https://download.rethinkdb.com/repository/ubuntu-bionic bionic main" > /etc/apt/sources.list.d/rethinkdb.list
apt update && apt install -y rethinkdb
```

Although I'm not a huge Ansible guru, I put together a playbook for you that installs RethinkDB perfectly on Bionic. Just for fun, I made a screen recording about this as well:

[![asciicast](https://asciinema.org/a/pG0zVXJzMcDgWqcvsdT7JWyU5.svg)](https://asciinema.org/a/pG0zVXJzMcDgWqcvsdT7JWyU5)

The playbook I used:

```yaml
---
- name: Install RethinkDB
  hosts: all
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        pkg:
        - gnupg
        - ca-certificates

    - name: Add RethinkDB keys
      apt_key: 
        id: 539A3A8C6692E6E3F69B3FE81D85E93F801BB43F
        keyserver: keyserver.ubuntu.com

    - name: Add RethinkDB repository
      apt_repository:
        repo: deb https://download.rethinkdb.com/repository/ubuntu-bionic bionic main
        state: present

    - name: Install RethinkDB
      apt:
        name: rethinkdb
        update_cache: yes
```
